version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      # to create/update an admin user at startup
      - USER_ADMIN_NAME=${USER_ADMIN_NAME}
      - USER_ADMIN_PASSWORD=${USER_ADMIN_PASSWORD}
      # to create/update a regular user at startup
      - USER_GUEST_NAME=${USER_GUEST_NAME}
      - USER_GUEST_PASSWORD=${USER_GUEST_PASSWORD}
    volumes:
      - /media:/media # support HDD
      - ./games:/games
      - ./config:/config
    ports:
      - "8465:8465"
