version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      # to create/update an admin user at startup
      - USER_ADMIN_NAME=admin
      - USER_ADMIN_PASSWORD=asdvnf!546XYZ
      # to create/update a regular user at startup
      - USER_GUEST_NAME=guest
      - USER_GUEST_PASSWORD=oerze!@8981XYZ
    volumes:
      - /media:/media
      - ./games:/games
      # - /dev/games:/games # Opcional cambiar a path de disco
      - ./config:/app/config
    ports:
      - "8465:8465"
